url: https://yarmoshyk.pro
baseurl: /
host: 0.0.0.0
incremental: true

# Site settings
title: Yarmoshyk Pro DevOps services
email: yaroslav@yarmoshyk.pro
description: "Cloud Expert, DevOps evangelist, CI/CD practitioner, IaaC adept, fan of Kubernetes"


# Team names, titles and social links
people:
- name: Yaroslav Yarmoshyk
  pic: 1
  position: CEO, Founder, Solutions Architect
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/yaroslav-yarmoshyk/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/yarmoshyk-pro-devops-services/
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: ul. Marsz. Józefa Piłsudskiego 74, lok. 320
  - line: Poland, Wrocław, , 50-020


# Build settings
markdown: kramdown
permalink: pretty